APP_NAME = 'Index Generator'
APP_VERSION = '0.2.9'
APP_URL = 'https://github.com/BruceZhang1993/index-generator'
PACKAGE_NAME = 'index-generator'
LICENSE = 'MIT'
AUTHOR = 'Bruce Zhang, Edward P'
EMAIL = ''
DESCRIPTION = 'Yet another index generator.'
